### ISSUE TITLE
musical-instruments, chime issue

### ISSUE THREAD

**Issue by johnwsha** [rayneong/hw4#2]
I don't have your chime assets so I can't run your code :(

**Comment by rayneong** [comment]
Hi John, thanks for checking in! The code's comment gives a link to the sketch, complete with assets: [http://alpha.editor.p5js.org/tinaye/sketches/Bk9NnIZDG](url) Let me know if there are any more issues.

**Comment by johnwsha** [comment]
I'm getting some other error now: 
https://puu.sh/zo92N/d053f7e19c.png

**Comment by rayneong** [comment]
Hi John, my own computer actually has the same error. Apparently, it breaks on certain computers and doesn't on others (my other team members can run it w/o issues). It seems like a bug in the p5 processor itself that I can't debug.

**Comment by rayneong** [comment]
Thanks for update! Atm, it looks like p5 breaks on Safari and Firefox :(

**Comment by rayneong** [comment]
And thanks for the comment :)
